### ISSUE TITLE
安全且方便地收集社团成员信息

### ISSUE THREAD

**Issue by chinggg** [shuopensourcecommunity/meta-OSC#5]
## 背景

社团年审时需要收集成员的信息，其中包括手机号、身份证号等个人隐私，目前有以下几种收集方法：

- 使用腾讯文档等公开的在线文档，直接发至群聊让所有人填写
  - 优点：只需每人填写一行，即可以表格形式汇总直接导出
  - 缺点：所有人的信息被公开暴露

- 成员将信息私聊发给给一位成员，由其汇总
  - 优点：只有一位成员获得其他成员的信息
  - 缺点：收集信息的同学需要额外统计并处理数据

- 制作一份问卷或收集表，每人填写，最终自动汇总导出
  - 优点：只有管理问卷的同学能看到其他成员的信息，且工作量小
  - 缺点：第三方平台能获得全部数据

这是一个开放式议题，请大家开动脑筋，表达自己的想法或提出一套切实可行的方案

**Comment by Chasing1020** [comment]
可以考虑使用slack发布问卷

**Comment by chinggg** [comment]
> 可以考虑使用slack发布问卷

Slack 问卷功能需通过第三方应用实现，Simple Poll免费版每月仅支持 10 次问卷和 5 个响应者，Polly 每月支持 25 次问卷
